use Spotify

DECLARE @json nvarchar(max)

set @json ='{
  "album_type": "single",
  "artists": [
    {
      "external_urls": {
        "spotify": "https://open.spotify.com/artist/3IniCa6EijyZ3bsY0eTG3C"
      },
      "href": "https://api.spotify.com/v1/artists/3IniCa6EijyZ3bsY0eTG3C",
      "id": "3IniCa6EijyZ3bsY0eTG3C",
      "name": "NCT 2020",
      "type": "artist",
      "uri": "spotify:artist:3IniCa6EijyZ3bsY0eTG3C"
    }
  ],
  "available_markets": [
    "AD",
    "AE",
    "AG",
    "AL",
    "AM",
    "AO",
    "AR",
    "AT",
    "AU",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BN",
    "BO",
    "BR",
    "BS",
    "BT",
    "BW",
    "BY",
    "BZ",
    "CH",
    "CI",
    "CL",
    "CM",
    "CO",
    "CR",
    "CV",
    "CW",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FJ",
    "FM",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GH",
    "GM",
    "GN",
    "GQ",
    "GR",
    "GT",
    "GW",
    "GY",
    "HK",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IS",
    "IT",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KR",
    "KW",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "MA",
    "MC",
    "MD",
    "ME",
    "MG",
    "MH",
    "MK",
    "ML",
    "MN",
    "MO",
    "MR",
    "MT",
    "MU",
    "MV",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NE",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PG",
    "PH",
    "PK",
    "PL",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RO",
    "RS",
    "RU",
    "RW",
    "SA",
    "SB",
    "SC",
    "SE",
    "SG",
    "SI",
    "SK",
    "SL",
    "SM",
    "SN",
    "SR",
    "ST",
    "SV",
    "SZ",
    "TD",
    "TG",
    "TH",
    "TL",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "UY",
    "UZ",
    "VC",
    "VN",
    "VU",
    "WS",
    "XK",
    "ZA",
    "ZM",
    "ZW"
  ],
  "copyrights": [
    {
      "text": "2020 SM Entertainment",
      "type": "C"
    },
    {
      "text": "2020 SM Entertainment",
      "type": "P"
    }
  ],
  "external_ids": {
    "upc": "888735936982"
  },
  "external_urls": {
    "spotify": "https://open.spotify.com/album/0wKPGjBd9uiJLQLDiQuNyT"
  },
  "genres": [],
  "href": "https://api.spotify.com/v1/albums/0wKPGjBd9uiJLQLDiQuNyT",
  "id": "0wKPGjBd9uiJLQLDiQuNyT",
  "images": [
    {
      "height": 640,
      "url": "https://i.scdn.co/image/ab67616d0000b273c17e48f4c875de91d750b012",
      "width": 640
    },
    {
      "height": 300,
      "url": "https://i.scdn.co/image/ab67616d00001e02c17e48f4c875de91d750b012",
      "width": 300
    },
    {
      "height": 64,
      "url": "https://i.scdn.co/image/ab67616d00004851c17e48f4c875de91d750b012",
      "width": 64
    }
  ],
  "label": "SM Entertainment",
  "name": "RESONANCE",
  "popularity": 58,
  "release_date": "2020-12-04",
  "release_date_precision": "day",
  "total_tracks": 1,
  "tracks": {
    "href": "https://api.spotify.com/v1/albums/0wKPGjBd9uiJLQLDiQuNyT/tracks?offset=0&limit=50",
    "items": [
      {
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/3IniCa6EijyZ3bsY0eTG3C"
            },
            "href": "https://api.spotify.com/v1/artists/3IniCa6EijyZ3bsY0eTG3C",
            "id": "3IniCa6EijyZ3bsY0eTG3C",
            "name": "NCT 2020",
            "type": "artist",
            "uri": "spotify:artist:3IniCa6EijyZ3bsY0eTG3C"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UY",
          "UZ",
          "VC",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
        ],
        "disc_number": 1,
        "duration_ms": 314120,
        "explicit": false,
        "external_urls": {
          "spotify": "https://open.spotify.com/track/6zAh5yF2pNYaAfqJtXQr2K"
        },
        "href": "https://api.spotify.com/v1/tracks/6zAh5yF2pNYaAfqJtXQr2K",
        "id": "6zAh5yF2pNYaAfqJtXQr2K",
        "is_local": false,
        "name": "RESONANCE",
        "preview_url": "https://p.scdn.co/mp3-preview/5c7538f22005b421204245fa8d8aa64daa38a43b?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:6zAh5yF2pNYaAfqJtXQr2K"
      }
    ],
    "limit": 50,
    "next": null,
    "offset": 0,
    "previous": null,
    "total": 1
  },
  "type": "album",
  "uri": "spotify:album:0wKPGjBd9uiJLQLDiQuNyT"
}'

INSERT INTO Albums SELECT Artist, Images, Title, Duration, IsExplicit, AlbumName FROM OPENJSON(@json) WITH
(
	Artist nvarchar(max) '$.artists[0].name',
	TrackItem nvarchar(max) '$.tracks.items' AS JSON,
	Images nvarchar(max) '$.images[0].url',
	AlbumName nvarchar(max) '$.name'
)
CROSS APPLY OPENJSON(TrackItem) WITH
(
	Title NVARCHAR(MAX) '$.name',
	Duration int '$.duration_ms',
	IsExplicit bit '$.explicit'
)