//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spotify.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public int SongID { get; set; }
        public string Artist { get; set; }
        public string Images { get; set; }
        public string Title { get; set; }
        public int Duration { get; set; }
        public bool IsExplicit { get; set; }
        public string AlbumName { get; set; }
        public string Year { get; set; }
    }
}
