//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spotify.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ArtistEntities : DbContext
    {
        public ArtistEntities()
            : base("name=ArtistEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artist> Artists { get; set; }
        public virtual DbSet<ArtistTopSong> ArtistTopSongs { get; set; }
    
        public virtual ObjectResult<QueryArtistTopSongs_Result> QueryArtistTopSongs(string artist)
        {
            var artistParameter = artist != null ?
                new ObjectParameter("artist", artist) :
                new ObjectParameter("artist", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<QueryArtistTopSongs_Result>("QueryArtistTopSongs", artistParameter);
        }
    }
}
