//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spotify.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public int ArtistID { get; set; }
        public string Artist1 { get; set; }
        public string Image { get; set; }
        public int Followers { get; set; }
    }
}
