//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spotify.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Playlist
    {
        public int PlaylistID { get; set; }
        public string PlaylistName { get; set; }
        public string PlaylistImage { get; set; }
        public int UserID { get; set; }
    }
}
