//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spotify.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Playlists { get; set; }
        public Nullable<int> Followers { get; set; }
        public Nullable<int> Following { get; set; }
        public string ProfilePic { get; set; }
        public string PasswordHash { get; set; }
        public string Username { get; set; }
    }
}
