//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spotify.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UserPlaylistEntities : DbContext
    {
        public UserPlaylistEntities()
            : base("name=UserPlaylistEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Playlist> Playlists { get; set; }
        public virtual DbSet<PlaylistSong> PlaylistSongs { get; set; }
    
        public virtual ObjectResult<QueryUserPlaylist_Result> QueryUserPlaylist(Nullable<int> userID, Nullable<int> playistID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var playistIDParameter = playistID.HasValue ?
                new ObjectParameter("PlayistID", playistID) :
                new ObjectParameter("PlayistID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<QueryUserPlaylist_Result>("QueryUserPlaylist", userIDParameter, playistIDParameter);
        }
    
        public virtual ObjectResult<QueryUserPlaylistName_Result> QueryUserPlaylistName(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<QueryUserPlaylistName_Result>("QueryUserPlaylistName", userIDParameter);
        }
    }
}
